### ISSUE TITLE
Missing var key_file

### ISSUE THREAD

**Issue by marcosgm** [mgmt-sa-tiger-team/lightbulb-windows#3]
ISSUE: when provisioning for the first time, following README instructions, I've found a missing variable (that's referenced many times in each ec2_windows_password call)

TASK [manage-ec2-instances : DomainController | Obtain windows passwords for instances] *****************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'key_file' is undefined\n\nThe error appears to have been in '/home/marcos/Projects/AZURE/lightbulb-windows/roles/manage-ec2-instances/tasks/provision.yml': line 441, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: DomainController | Obtain windows passwords for instances\n  ^ here\n"}

https://docs.ansible.com/ansible/2.3/ec2_win_password_module.html
key_file is "Path to the file containing the key pair used on the instance."

FIXED adding a new variable in vars/vars.yml
key_file: "~/CREDENTIALS/net-ws_key"
the same as 
ec2_key_file: "~/CREDENTIALS/net-ws_key"

**Comment by cigamit** [comment]
Thanks.  Fixed this by changing it to use ec2_key_file.
