### ISSUE TITLE
Generate instructor inventory fails with "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_host'"

### ISSUE THREAD

**Issue by magicalyak** [mgmt-sa-tiger-team/lightbulb-windows#4]
When using develop on ec2, there is an error on the inventory file where ansible complains about ansible_host being undefined.  I see ansible_host facts for the vms but I still get the error.

`TASK [manage-ec2-instances : Generate instructor inventory] ***************************************************************************
task path: /Users/tgamull/Documents/GitHub/lightbulb-windows/roles/manage-ec2-instances/tasks/provision.yml:543
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tgamull
<127.0.0.1> EXEC /bin/sh -c 'echo ~tgamull && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/tgamull/.ansible/tmp/ansible-tmp-1528761702.96-125354823242559 `" && echo ansible-tmp-1528761702.96-125354823242559="` echo /Users/tgamull/.ansible/tmp/ansible-tmp-1528761702.96-125354823242559 `" ) && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/tgamull/.ansible/tmp/ansible-tmp-1528761702.96-125354823242559/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_host'"
}
	to retry, use: --limit @/Users/tgamull/Documents/GitHub/lightbulb-windows/site.retry

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=32   changed=14   unreachable=0    failed=1   
`

**Comment by cigamit** [comment]
What Ansible version?  We literally set that variable for each host here
https://github.com/mgmt-sa-tiger-team/lightbulb-windows/blob/develop/roles/manage-ec2-instances/tasks/provision.yml#L481

Can you do a debug print of your hostvars right before that task?

**Comment by magicalyak** [comment]
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/tgamull/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May 21 2018, 10:00:57) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

I have to run it again for the hostvars but I saw ansible_host in there

**Comment by magicalyak** [comment]
`TASK [manage-ec2-instances : Workstation | Add new instance to host group] ************************************************************
task path: /Users/tgamull/Documents/GitHub/lightbulb-windows/roles/manage-ec2-instances/tasks/provision.yml:525
creating host via 'add_host': hostname=skylight-s1workstation
changed: [localhost] => (item={'_ansible_parsed': True, u'changed': True, '_ansible_no_log': False, 'item': {u'kernel': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-10-0-0-120.ec2.internal', u'public_ip': u'54.90.95.176', u'private_ip': u'10.0.0.120', u'id': u'i-0af885d05a594fdd7', u'ebs_optimized': False, u'state': u'running', u'virtualization_type': u'hvm', u'root_device_name': u'/dev/sda1', u'ramdisk': None, u'block_device_mapping': {u'/dev/sda1': {u'status': u'attached', u'delete_on_termination': True, u'volume_id': u'vol-0cd45776a11dd9d8f'}}, u'key_name': u'mykeypair', u'image_id': u'ami-013e197b', u'tenancy': u'default', u'groups': {u'sg-71c0323a': u'skylight-windowssg'}, u'public_dns_name': u'ec2-54-90-95-176.compute-1.amazonaws.com', u'state_code': 16, u'tags': {u'App': u'AnsibleWorkshop', u'User': u'student1', u'Name': u'skylight-s1workstation'}, u'placement': u'us-east-1b', u'ami_launch_index': u'0', u'dns_name': u'ec2-54-90-95-176.compute-1.amazonaws.com', u'region': u'us-east-1', u'launch_time': u'2018-06-12T14:05:06.000Z', u'instance_type': u't2.medium', u'architecture': u'x86_64', u'hypervisor': u'xen'}, '_ansible_item_result': True, u'elapsed': 0, 'failed': False, u'invocation': {u'module_args': {u'profile': None, u'aws_secret_key': None, u'aws_access_key': None, u'security_token': None, u'region': u'us-east-1', u'instance_id': u'i-0af885d05a594fdd7', u'key_passphrase': None, u'wait_timeout': 45, u'ec2_url': None, u'key_file': u'/Users/tgamull/.ssh/mykeypair.pem', u'validate_certs': True, u'wait': True}}, u'win_password': u')fgqc5je4@', '_ansible_ignore_errors': None}) => {
    "add_host": {
        "groups": [
            "windows_workstations"
        ], 
        "host_name": "skylight-s1workstation", 
        "host_vars": {
            "ansible_connection": "winrm", 
            "ansible_host": "54.90.95.176", 
            "ansible_password": ")fgqc5je4@", 
            "ansible_port": 5986, 
            "ansible_user": "Administrator", 
            "ansible_winrm_server_cert_validation": "ignore", 
            "ansible_winrm_transport": "ntlm", 
            "private_ip": "10.0.0.120"
        }
    }, 
    "changed": true, 
    "item": {
        "changed": true, 
        "elapsed": 0, 
        "failed": false, 
        "invocation": {
            "module_args": {
                "aws_access_key": null, 
                "aws_secret_key": null, 
                "ec2_url": null, 
                "instance_id": "i-0af885d05a594fdd7", 
                "key_file": "/Users/tgamull/.ssh/mykeypair.pem", 
                "key_passphrase": null, 
                "profile": null, 
                "region": "us-east-1", 
                "security_token": null, 
                "validate_certs": true, 
                "wait": true, 
                "wait_timeout": 45
            }
        }, 
        "item": {
            "ami_launch_index": "0", 
            "architecture": "x86_64", 
            "block_device_mapping": {
                "/dev/sda1": {
                    "delete_on_termination": true, 
                    "status": "attached", 
                    "volume_id": "vol-0cd45776a11dd9d8f"
                }
            }, 
            "dns_name": "ec2-54-90-95-176.compute-1.amazonaws.com", 
            "ebs_optimized": false, 
            "groups": {
                "sg-71c0323a": "skylight-windowssg"
            }, 
            "hypervisor": "xen", 
            "id": "i-0af885d05a594fdd7", 
            "image_id": "ami-013e197b", 
            "instance_type": "t2.medium", 
            "kernel": null, 
            "key_name": "mykeypair", 
            "launch_time": "2018-06-12T14:05:06.000Z", 
            "placement": "us-east-1b", 
            "private_dns_name": "ip-10-0-0-120.ec2.internal", 
            "private_ip": "10.0.0.120", 
            "public_dns_name": "ec2-54-90-95-176.compute-1.amazonaws.com", 
            "public_ip": "54.90.95.176", 
            "ramdisk": null, 
            "region": "us-east-1", 
            "root_device_name": "/dev/sda1", 
            "root_device_type": "ebs", 
            "state": "running", 
            "state_code": 16, 
            "tags": {
                "App": "AnsibleWorkshop", 
                "Name": "skylight-s1workstation", 
                "User": "student1"
            }, 
            "tenancy": "default", 
            "virtualization_type": "hvm"
        }, 
        "win_password": "XXXXXXX"
    }
}
Read vars_file '[u'vars/custom.yml', u'vars/main.yml']'`

**Comment by magicalyak** [comment]
TASK [manage-ec2-instances : Workstation | Add new instance to host group] ************************************************************
task path: /Users/tgamull/Documents/GitHub/lightbulb-windows/roles/manage-ec2-instances/tasks/provision.yml:525
creating host via 'add_host': hostname=skylight-s1workstation
changed: [localhost] => (item={'_ansible_parsed': True, u'changed': True, '_ansible_no_log': False, 'item': {u'kernel': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-10-0-0-120.ec2.internal', u'public_ip': u'54.90.95.176', u'private_ip': u'10.0.0.120', u'id': u'i-0af885d05a594fdd7', u'ebs_optimized': False, u'state': u'running', u'virtualization_type': u'hvm', u'root_device_name': u'/dev/sda1', u'ramdisk': None, u'block_device_mapping': {u'/dev/sda1': {u'status': u'attached', u'delete_on_termination': True, u'volume_id': u'vol-0cd45776a11dd9d8f'}}, u'key_name': u'mykeypair', u'image_id': u'ami-013e197b', u'tenancy': u'default', u'groups': {u'sg-71c0323a': u'skylight-windowssg'}, u'public_dns_name': u'ec2-54-90-95-176.compute-1.amazonaws.com', u'state_code': 16, u'tags': {u'App': u'AnsibleWorkshop', u'User': u'student1', u'Name': u'skylight-s1workstation'}, u'placement': u'us-east-1b', u'ami_launch_index': u'0', u'dns_name': u'ec2-54-90-95-176.compute-1.amazonaws.com', u'region': u'us-east-1', u'launch_time': u'2018-06-12T14:05:06.000Z', u'instance_type': u't2.medium', u'architecture': u'x86_64', u'hypervisor': u'xen'}, '_ansible_item_result': True, u'elapsed': 0, 'failed': False, u'invocation': {u'module_args': {u'profile': None, u'aws_secret_key': None, u'aws_access_key': None, u'security_token': None, u'region': u'us-east-1', u'instance_id': u'i-0af885d05a594fdd7', u'key_passphrase': None, u'wait_timeout': 45, u'ec2_url': None, u'key_file': u'/Users/tgamull/.ssh/mykeypair.pem', u'validate_certs': True, u'wait': True}}, u'win_password': u')fgqc5je4@', '_ansible_ignore_errors': None}) => {
    "add_host": {
        "groups": [
            "windows_workstations"
        ], 
        "host_name": "skylight-s1workstation", 
        "host_vars": {
            "ansible_connection": "winrm", 
            "ansible_host": "54.90.95.176", 
            "ansible_password": "XXXXXX", 
            "ansible_port": 5986, 
            "ansible_user": "Administrator", 
            "ansible_winrm_server_cert_validation": "ignore", 
            "ansible_winrm_transport": "ntlm", 
            "private_ip": "10.0.0.120"
        }
    }, 
    "changed": true, 
    "item": {
        "changed": true, 
        "elapsed": 0, 
        "failed": false, 
        "invocation": {
            "module_args": {
                "aws_access_key": null, 
                "aws_secret_key": null, 
                "ec2_url": null, 
                "instance_id": "i-0af885d05a594fdd7", 
                "key_file": "/Users/tgamull/.ssh/mykeypair.pem", 
                "key_passphrase": null, 
                "profile": null, 
                "region": "us-east-1", 
                "security_token": null, 
                "validate_certs": true, 
                "wait": true, 
                "wait_timeout": 45
            }
        }, 
        "item": {
            "ami_launch_index": "0", 
            "architecture": "x86_64", 
            "block_device_mapping": {
                "/dev/sda1": {
                    "delete_on_termination": true, 
                    "status": "attached", 
                    "volume_id": "vol-0cd45776a11dd9d8f"
                }
            }, 
            "dns_name": "ec2-54-90-95-176.compute-1.amazonaws.com", 
            "ebs_optimized": false, 
            "groups": {
                "sg-71c0323a": "skylight-windowssg"
            }, 
            "hypervisor": "xen", 
            "id": "i-0af885d05a594fdd7", 
            "image_id": "ami-013e197b", 
            "instance_type": "t2.medium", 
            "kernel": null, 
            "key_name": "mykeypair", 
            "launch_time": "2018-06-12T14:05:06.000Z", 
            "placement": "us-east-1b", 
            "private_dns_name": "ip-10-0-0-120.ec2.internal", 
            "private_ip": "10.0.0.120", 
            "public_dns_name": "ec2-54-90-95-176.compute-1.amazonaws.com", 
            "public_ip": "54.90.95.176", 
            "ramdisk": null, 
            "region": "us-east-1", 
            "root_device_name": "/dev/sda1", 
            "root_device_type": "ebs", 
            "state": "running", 
            "state_code": 16, 
            "tags": {
                "App": "AnsibleWorkshop", 
                "Name": "skylight-s1workstation", 
                "User": "student1"
            }, 
            "tenancy": "default", 
            "virtualization_type": "hvm"
        }, 
        "win_password": "XXXXXXX"
    }
}
Read vars_file '[u'vars/custom.yml', u'vars/main.yml']'

**Comment by cigamit** [comment]
I will have to test it on Ansible 2.5, this was originally developed on 2.4 and I have noticed lots of broken things between those versions.

**Comment by magicalyak** [comment]
I can retry with 2.4 on a vm tomorrow, I'll post results.

**Comment by magicalyak** [comment]
2.4 appears to get through the error.  I have found 2 unrelated issues
1) it appears the playbook has trouble with the new long vpc and subnet names
2) the Windows DC install is failing after
Create DNS Domain
Reboot if Needed (timeout)

I had a timeout on the first run with Install AD-Domain-Service, I may make the timeout for the sleep 3 minutes...sigh 5 minutes

I am running through the playbook again

**Comment by cigamit** [comment]
fcb7a8f This fixes the .Net Opt issue at least, now to fix the timeout issue after creating the DNS Domain

**Comment by magicalyak** [comment]
I'm hitting this, I'm guessing it's the same?
PLAY [Configure Active Directory Domain Controller] ***********************************************************************************
META: ran handlers
Read vars_file '[u'vars/custom.yml', u'vars/main.yml']'

TASK [windows-ad-controller : Sleep 3 minutes before attempting to install... sigh...] ************************************************
task path: /root/lightbulb-windows/roles/windows-ad-controller/tasks/main.yml:2
Pausing for 180 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [windc] => {
    "changed": false, 
    "delta": 180, 
    "failed": false, 
    "rc": 0, 
    "start": "2018-06-14 10:09:48.227018", 
    "stderr": "", 
    "stdout": "Paused for 3.0 minutes", 
    "stop": "2018-06-14 10:12:48.227336", 
    "user_input": ""
}
Read vars_file '[u'vars/custom.yml', u'vars/main.yml']'

TASK [windows-ad-controller : Install AD-Domain-Services] *****************************************************************************
task path: /root/lightbulb-windows/roles/windows-ad-controller/tasks/main.yml:6
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_feature.ps1
<52.87.237.8> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 52.87.237.8
checking if winrm_host 52.87.237.8 is an IPv6 address
fatal: [windc]: UNREACHABLE! => {
    "changed": false, 
    "msg": "ntlm: HTTPSConnectionPool(host='52.87.237.8', port=5986): Read timed out. (read timeout=30)", 
    "unreachable": true
}
	to retry, use: --limit @/root/lightbulb-windows/site.retry

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=34   changed=14   unreachable=0    failed=0   
windc                      : ok=1    changed=0    unreachable=1    failed=0

**Comment by cigamit** [comment]
Yep, looks like the WinRM connection is dropping.  My VMWare and Azure instances don't seem to do this, only the EC2 ones.  I am debugging it now.  Seems like the WinRM service is getting restarted when it installs DNS.  I tested upping the timeout and that didn't work, so now I will try adding a wait_for_connection there and see if it has any effect.  Other option is to add some retries.

**Comment by magicalyak** [comment]
What ami are you using?

**Comment by cigamit** [comment]
ami-013e197b
Right now the one you posted above.

**Comment by magicalyak** [comment]
Interesting, trying to mstsc from the wokstation to the domain on the local
ip gives a network login service isn't started

**Comment by cigamit** [comment]
Yep, I found the same thing.  The service itself failed, which then causes authentication to timeout.  I am trying a few fixes for it now.

**Comment by magicalyak** [comment]
Any relation to this issue in vmware?
https://docs.vmware.com/en/VMware-Horizon-7/7.3/horizon-virtual-desktops/GUID-638E6B6C-0E31-4754-9CF0-22609FF6EB46.html

**Comment by cigamit** [comment]
I added a fix for this the other day.  This only happens on AWS and it happens to every AMI I have tried. 
 There really isn't much we can do about it via WinRM, so I added a EC2 restart in there to get around it.

Give it another go and see if it works for you.
